In [3]:
#import required libraries
import numpy as np
from numpy.linalg import norm

#define two lines or array
A=np.array([2,1,2,3,2,9])
B=np.array([3,4,2,4,5,5])

print("A:",A)
print("B:",B)

#compute cosine similarity
cosine=np.dot(A,B)/(norm(A)*norm(B))
print("cosine similarity:",cosine)

A: [2 1 2 3 2 9]
B: [3 4 2 4 5 5]
cosine similarity: 0.8188504723485274


In [5]:
#import required libraries
import numpy as np
from numpy.linalg import norm

#define two lines or array
A=np.array([[2,1,2],[3,2,9],[-1,2,-3]])
B=np.array([3,4,2])
print("A:\n",A)
print("A:\n",B)

# compute cosine similarity
cosine = np.dot(A,B)/(norm(A, axis=1)*norm(B))
print("Cosine Similarity:\n", cosine)


A:
 [[ 2  1  2]
 [ 3  2  9]
 [-1  2 -3]]
A:
 [3 4 2]
Cosine Similarity:
 [ 0.86657824  0.67035541 -0.04962917]


In [8]:
# import required libraries
import numpy as np
from numpy.linalg import norm
# define two arrays
A = np.array([[1,2,2],[3,2,2],[-2,1,-3]])
B = np.array([[4,2,4],[2,-2,5],[3,4,-4]])
print("A:\n", A)
print("B:\n", B)

# compute cosine similarity
cosine = np.sum(A*B, axis=1)/(norm(A, axis=1)*norm(B, axis=1))
print("Cosine Similarity:\n", cosine)
print("Cosine Similarity:\n", cosine)

A:
 [[ 1  2  2]
 [ 3  2  2]
 [-2  1 -3]]
B:
 [[ 4  2  4]
 [ 2 -2  5]
 [ 3  4 -4]]
Cosine Similarity:
 [0.88888889 0.5066404  0.41739194]
Cosine Similarity:
 [0.88888889 0.5066404  0.41739194]
