In [2]:
import numpy as np
# creating a array
arr = np.array([1,2,3])
print(arr)

# creating array 2
arr = np.array ([[1,2,3,],[4,5,6]])
print (arr)

# creating an array from tuple
arr = np.array((1,2,3,))
print(arr)



[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 2 3]


In [3]:
a=  np.array([[1,2],[3,4]])
b=  np.array([[4,3],[2,1]])
# adding 1 to every element
print("Adding 1 to every element", a+1)
#Substract 2 to every element 
print("Substracting 2 to every element", b-2)
#sum of array elements
print("\n sum of all elements", a.sum())
#Adding to array 
print("\n Array sum\n", a+b)

Adding 1 to every element [[2 3]
 [4 5]]
Substracting 2 to every element [[ 2  1]
 [ 0 -1]]

 sum of all elements 10

 Array sum
 [[5 5]
 [5 5]]


In [4]:
#Integer datatype
x= np.array([1,2,3])
print(x.dtype)
#floot datatype
x=np.array([1.0,2.0])
print(x.dtype)

int64
float64


In [8]:
import numpy as np

a1_zeros = np.zeros((3,2))
a2_ones = np.ones((2,2))
a3_range = np.arange(0, 10, 2)

print(a1_zeros)
print(a2_ones)
print(a3_range)


[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]


In [10]:
import numpy as np
 # create a 1D array
arr1d = np.array([12, 20, 30, 40, 50])

# single element access
print("single element access:",arr1d[2])

#negative indexing
print("negative indexing:",arr1d[-1])

#create 2d array
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

#multidimrnsional array access
print("multidimrnsional array access:",arr2d[1,0])

single element access: 30
negative indexing: 50
multidimrnsional array access: 4


In [11]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
#elements from index 1 to 3
print("range of element:",arr[1:4])

#all rows,second colum
print("multidimrnsional slicing:", arr[:,1])

range of element: [[4 5 6]]
multidimrnsional slicing: [2 5]


In [12]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90,100])

#integer array indexing
indices = np.array([1,3,5])
print("integer array indexing:",[indices])

#boolean array indexing
cond =arr > 0
print("\n elements greater then 0:\n", arr[cond])

integer array indexing: [array([1, 3, 5])]

 elements greater then 0:
 [ 10  20  30  40  50  60  70  80  90 100]
